services:
    phpbb_bridge.command.cache:
        class: Ctsmedia\Phpbb\BridgeBundle\Command\CacheCommand
        arguments:
            - '@phpbb_bridge.connector'
        tags:
            -  { name: console.command }
